# Generated by Django 5.0.8 on 2025-01-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('health', 'Health'), ('tourism', 'Tourism'), ('finance', 'Finance'), ('games', 'Games')], max_length=10)),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('html_css', 'HTML/CSS')], max_length=10)),
                ('prompt_type', models.CharField(choices=[('debugging', 'Debugging'), ('documentation', 'Documentation'), ('generation', 'Generation')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
