# Generated by Django 5.0.8 on 2025-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
